export const ADD_USER = "ADD_USER";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const GET_CONVERSATION = "GET_CONVERSATION";
export const GET_MESSAGES = "GET_MESSAGES";
export const LOADING_MESSAGES = "LOADING_MESSAGES";
