export const GET_NOTIFICATION = 'GET_NOTIFICATION'
export const LOADING = 'LOADING_NOTIFICATION'
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const ISREAD_NOTIFICATION = 'ISREAD_NOTIFICATION'
export const SOUND_NOTIFICATION = 'SOUND_NOTIFICATION'
export const DELETE_ALL_NOTIFICATION = 'DELETE_ALL_NOTIFICATION'



